title: Sant Jordi Jam
author: Sant Jordi Jam
email: santjordijam@gmail.com
description: >-
  Lloc web de la Sant Jordi Jam.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://santjordijam.github.io" # your site's origin, e.g. https://forestry.io
keyword: "Sant Jordi Jam, Sant Jordi, Game Jam, Video Games"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

